name: My workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install required packages
      run: pip install -r requirements.txt

    - name: Set up virtual display
      uses: xvfb-action/xvfb@v1
      with:
        run: |
          sudo apt-get install -y chromium-browser
          export CHROME_BIN=chromium-browser
          export DISPLAY=:99

    - name: Run tests
      run: python run-sitemap.py
