name: Selenium Test

on:
  push:
    branches:
      - main # 这里可以指定要触发的分支

jobs:
  test:
    runs-on: ubuntu-latest # 运行环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 # 从 GitHub 拉取代码

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # 这里的 requirements.txt 是指定的 Python 依赖文件，需要放在代码仓库的根目录下

    - name: Download and install ChromeDriver
      run: |
        CHROME_DRIVER_VERSION=`curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE`
        wget -q -O - "https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip" | bsdtar -xvf - -C /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver # 下载和安装 ChromeDriver

    - name: Run Selenium tests
      run: |
        python run-sitemap.py # 这里的 test.py 是要执行的测试脚本，需要放在代码仓库的根目录下
